/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WW5ZFDcQU8Z
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";
import { cn } from "@/lib/utils";

export function FacebookLanding({
  action,
  className,
  ...props
}: React.ComponentPropsWithoutRef<"form">) {
  return (
    <form
      className={cn(
        "flex min-h-screen items-center justify-center bg-[#f0f2f5] p-4",
        className,
      )}
      {...props}
      action={action}
    >
      <div className="space-y-8">
        <div className="text-center">
          <h2 className="text-5xl font-bold text-[#1877f2]">facebook</h2>
          <p className="mt-3 text-lg">
            Connect with friends and the world around you on Facebook.
          </p>
        </div>
        <Card className="mx-auto w-[400px]">
          <CardContent className="pt-6">
            <div className="space-y-4">
              <Input placeholder="Email or phone number" type="text" />
              <Input placeholder="Password" type="password" />
              <Button
                className="w-full bg-[#1877f2] hover:bg-[#1877f2]/70 text-white"
                type="submit"
              >
                Log In
              </Button>
            </div>
            <div className="mt-3 text-center">
              <button className="text-sm text-[#1877f2]" type="submit">
                Forgot password?
              </button>
            </div>
            <div className="my-4 flex justify-center">
              <div className="h-[1px] w-full bg-gray-300" />
            </div>
            <div className="text-center">
              <Button
                className="bg-[#42b72a] hover:bg-[#42b72a]/70 text-white"
                type="submit"
              >
                Create new account
              </Button>
            </div>
          </CardContent>
        </Card>
        <div className="text-center">
          <button className="text-sm text-[#1877f2] mr-2" type="submit">
            Create a Page
          </button>
          for a celebrity, brand or business.{"\n"}
        </div>
      </div>
    </form>
  );
}
