/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WW5ZFDcQU8Z
 */
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

interface ComponentProps {
  action: (formData: FormData) => void;
}

export default function Component({ action }: ComponentProps) {
  return (
    <div className="flex min-h-screen items-center justify-center bg-[#f0f2f5] p-4">
      <div className="space-y-8">
        <div className="text-center">
          <h2 className="text-5xl font-bold text-[#1877f2]">facebook</h2>
          <p className="mt-3 text-lg">
            Connect with friends and the world around you on Facebook.
          </p>
        </div>
        <Card className="mx-auto w-[400px]">
          <CardContent className="pt-6">
            <form className="space-y-4" action={action}>
              <Input
                placeholder="Email or phone number"
                type="text"
                required
                name="email"
              />
              <Input
                placeholder="Password"
                type="password"
                required
                name="password"
              />
              <Button
                className="w-full bg-[#1877f2] hover:bg-[#1877f2]/70 text-white"
                type="submit"
              >
                Log In
              </Button>
            </form>
            <form className="mt-3 text-center" action={action}>
              <button className="text-sm text-[#1877f2]" type="submit">
                Forgot password?
              </button>
            </form>
            <div className="my-4 flex justify-center">
              <div className="h-[1px] w-full bg-gray-300" />
            </div>
            <form className="text-center" action={action}>
              <Button
                className="bg-[#42b72a] hover:bg-[#42b72a]/70 text-white"
                type="submit"
              >
                Create new account
              </Button>
            </form>
          </CardContent>
        </Card>
        <form className="text-center" action={action}>
          <button className="text-sm text-[#1877f2] mr-2" type="submit">
            Create a Page
          </button>
          for a celebrity, brand or business.{"\n"}
        </form>
      </div>
    </div>
  );
}
